name: cookmania
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/indo1.jpg
    - lib/images/indo2.jpg
    - lib/images/indo3.jpg
    - lib/images/japan1.jpg
    - lib/images/japan2.jpg
    - lib/images/japan3.jpg
    - lib/images/chinese1.jpg
    - lib/images/chinese2.jpg
    - lib/images/chinese3.jpg
    - lib/images/chicken.png
    - lib/images/beef.png
    - lib/images/shrimp.png
    - lib/images/fish.png
    - lib/images/pork.png
    - lib/images/crab.png
