name: cookmania
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/itali1.jpg
    - lib/images/itali2.jpg
    - lib/images/japan1.jpg
    - lib/images/japan2.jpg
    - lib/images/korea1.jpg
    - lib/images/korea2.jpg
    - lib/images/chicken.png
    - lib/images/beef.png
    - lib/images/shrimp.png
    - lib/images/fish.png
    - lib/images/pork.png
    - lib/images/crab.png
