// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClny5TkBxjdDbIg1bq0U3Qe0SY_slJadw',
    appId: '1:290024013907:web:d16b97d76dc4506cf146a6',
    messagingSenderId: '290024013907',
    projectId: 'flutter-cookmania',
    authDomain: 'flutter-cookmania.firebaseapp.com',
    databaseURL: 'https://flutter-cookmania-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-cookmania.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGUDzkaEaMfHUNk20p4BF8Y6q8pOSGAGE',
    appId: '1:290024013907:android:c67a3abdf764eadef146a6',
    messagingSenderId: '290024013907',
    projectId: 'flutter-cookmania',
    databaseURL: 'https://flutter-cookmania-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-cookmania.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz_Lb2Dqu_6ho8VTPmjlkNCXyKsmtvSAc',
    appId: '1:290024013907:ios:25254db741c58c64f146a6',
    messagingSenderId: '290024013907',
    projectId: 'flutter-cookmania',
    databaseURL: 'https://flutter-cookmania-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-cookmania.appspot.com',
    iosBundleId: 'com.example.cookmania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz_Lb2Dqu_6ho8VTPmjlkNCXyKsmtvSAc',
    appId: '1:290024013907:ios:25254db741c58c64f146a6',
    messagingSenderId: '290024013907',
    projectId: 'flutter-cookmania',
    databaseURL: 'https://flutter-cookmania-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-cookmania.appspot.com',
    iosBundleId: 'com.example.cookmania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClny5TkBxjdDbIg1bq0U3Qe0SY_slJadw',
    appId: '1:290024013907:web:bb90ce1664cb53c0f146a6',
    messagingSenderId: '290024013907',
    projectId: 'flutter-cookmania',
    authDomain: 'flutter-cookmania.firebaseapp.com',
    databaseURL: 'https://flutter-cookmania-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-cookmania.appspot.com',
  );
}
